### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by samehhady** [Necromancer1982/SmartSwitch#3]
Thanks for sharing this great project, I was looking for something very simple.
Tell me are you interested for some small freelance work with a very small modification to this board?

I really tried to find a mail for you or a way to message you but this was my best choice :)

**Comment by Necromancer1982** [comment]
Hi,

Now, there is a mail address avaliable on my profile!

Sorry for my late reply, but I was on parental leave and nearly didn't touch my computer during the last weeks :-)

Actually I have a lot of work on my new house and also the garden.
Therefore it's hard to do some freelance work at the moment. 
What are you interested in?

PS: I'll close the Issue, please contact me via email
