### ISSUE TITLE
Platinen oder Gerber Files?

### ISSUE THREAD

**Issue by Tommy-LSA** [Necromancer1982/SmartSwitch#5]
Hallo,
Ist es möglich, 10 Platinen zu bekommen, oder die Gerber Files um selbst welche bei itead.cc zu ordern? Ich würde gerne unsere Rolläden im Haus über Tasmota und FHEM steuern. Du scheinst der Einzige zu sein, der eine passende Hardware entwickelt hat. Ich komme eher aus der Software Ecke und habe mit Platinen (erstellen/bestellen) nicht viel am Hut. Das Löten traue ich mir noch zu, anhand Deiner sehr guten Dokumentation.
Danke, das Du das Projekt veröffentlicht hast.

**Comment by leschNUX** [comment]
Hi,

Ich hab noch welche, wenn du mir deine Mailadresse schickst, kann ich dir welche schicken!

**Comment by Tommy-LSA** [comment]
Oh, das wär super. Mailadresse ist: pirat(im)stadtweg(in)de

**Comment by Necromancer1982** [comment]
Hi,
sorry, war im Urlaub und damit länger nicht mehr auf GitHub...
Die CAM-Files sind bereits im Repo.
Mit diesen kannst du direkt bei itead bestellen.

Gruß Andreas
